defmodule AdventOfCode.Day11Test do
  use ExUnit.Case

  doctest AdventOfCode.Day11

  @input """
  ...#......
  .......#..
  #.........
  ..........
  ......#...
  .#........
  .........#
  ..........
  .......#..
  #...#.....
  """

  test "part 1" do
    assert AdventOfCode.Day11.solve(@input, part: 1) == 374
  end
end
